version: '3.7'
services:

  nf:
    image: naive_feedya_dev
    container_name: naive_feedya
    # user: root
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV_MODE=true
    restart: always
    # command: jupyter-notebook --ip=0.0.0.0 --no-browser --notebook-dir="/"
    command: python main.py
    ports:
      # - "8888:8888"
      - "8008:8008"
    volumes:
      - ./app/:/home/app/app/
      - ./notebooks/:/mnt/notebooks/
      - ./cache/:/var/lib/naive_feedya/