version: '3.7'
services:

  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    hostname: reproxy
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Belarus/Minsk
      - DOCKER_ENABLED=true
      - SSL_TYPE=auto
      - SSL_ACME_FQDN=example.com
      - LOGGER_ENABLED=true
      - HEADER=
          X-Frame-Options:SAMEORIGIN,
          X-XSS-Protection:1; mode=block;,
          Content-Security-Policy:default-src 'self'; style-src 'self' 'unsafe-inline';

  nf:
    image: naive_feedya
    container_name: naive_feedya
    hostname: naive-feedya
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - reproxy
    labels:
      reproxy.server: '*'
      reproxy.route: '^/(.*)'
      reproxy.dest: '/@1'
    volumes:
      - ./cache:/var/lib/naive_feedya